# Generated by Django 2.2 on 2020-02-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltexamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='beltexamapp.User'),
        ),
    ]
